import React, { useEffect, useMemo, useState } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, Plus, Repeat2, Sparkles, X } from 'lucide-react';

const TZ = 'Asia/Jakarta';
const dateKey = (value) => new Intl.DateTimeFormat('en-CA', { timeZone: TZ }).format(new Date(value));
const prettyDate = (value) => new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium', timeStyle: 'short', timeZone: TZ }).format(new Date(value));
const initialForm = (type, brandId = '') => ({
    name: '', schedule_type: type, platform: 'instagram', content_type: 'post', topic: '', brief: '', assigned_agent: '', timezone: TZ,
    brand_id: brandId, scheduled_at: '', frequency: 'weekly', days: [1], time: '09:00', starts_at: new Date().toISOString().slice(0, 10), ends_at: '', generation_mode: 'manual', publishing_mode: 'review', is_active: true,
});

function PlannerForm({ type, brands, onClose, onSave }) {
    const [form, setForm] = useState(() => initialForm(type, brands[0]?.id));
    const [saving, setSaving] = useState(false);
    const [error, setError] = useState(null);
    const change = (key, value) => setForm(current => ({ ...current, [key]: value }));
    const toggleDay = (day) => change('days', form.days.includes(day) ? form.days.filter(item => item !== day) : [...form.days, day]);
    const save = async (event) => { event.preventDefault(); setSaving(true); setError(null); try { await onSave(form); onClose(); } catch (caught) { setError(caught.message); } finally { setSaving(false); } };
    const datePart = form.scheduled_at.slice(0, 10);
    const timePart = form.scheduled_at.slice(11, 16);
    const setWhen = (part, value) => change('scheduled_at', `${part === 'date' ? value : datePart}T${part === 'time' ? value : timePart}`);
    const brand = brands.find(item => item.id === form.brand_id);
    const summary = type === 'one_time' ? (form.scheduled_at ? prettyDate(form.scheduled_at) : 'Choose a date and time') : `${form.frequency === 'weekly' ? `Every ${form.days.map(day => ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][day - 1]).join(', ')}` : form.frequency === 'monthly' ? 'Every month' : 'Every day'} at ${form.time}`;
    return <div className="planner-modal-wrap"><button type="button" className="planner-modal-scrim" onClick={onClose} aria-label="Tutup formulir" /><form className="planner-modal" onSubmit={save}>
        <header><div><span>{type === 'recurring' ? 'RECURRING SCHEDULE' : 'ONE-TIME SCHEDULE'}</span><h2>{type === 'recurring' ? 'Add recurring content' : 'Schedule content'}</h2></div><button type="button" onClick={onClose}><X size={18} /></button></header>
        <section className="planner-form-section"><span>BASIC</span><label>Workspace / Brand<select required value={form.brand_id} onChange={e => change('brand_id', e.target.value)}><option value="" disabled>Select a workspace</option>{brands.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><div className="planner-form-grid"><label>Platform<select value={form.platform} onChange={e => change('platform', e.target.value)}><option>instagram</option><option>linkedin</option><option>twitter</option><option>blog</option></select></label><label>Content type<input required value={form.content_type} onChange={e => change('content_type', e.target.value)} placeholder="feed, story, article" /></label></div><label>Topic / title<input required value={form.name} onChange={e => { change('name', e.target.value); change('topic', e.target.value); }} placeholder="Active Recall Tips" /></label></section>
        {type === 'one_time' ? <section className="planner-form-section"><span>WHEN</span><div className="planner-form-grid"><label>Date<input required type="date" value={datePart} onChange={e => setWhen('date', e.target.value)} /></label><label>Time<input required type="time" value={timePart} onChange={e => setWhen('time', e.target.value)} /></label></div></section> : <section className="planner-form-section"><span>SCHEDULE</span><div className="planner-form-grid"><label>Frequency<select value={form.frequency} onChange={e => change('frequency', e.target.value)}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><label>Time<input required type="time" value={form.time} onChange={e => change('time', e.target.value)} /></label></div>{form.frequency === 'weekly' && <fieldset><legend>Weekdays</legend><div className="weekday-picker">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map((label, index) => <button type="button" className={form.days.includes(index + 1) ? 'selected' : ''} onClick={() => toggleDay(index + 1)} key={label}>{label}</button>)}</div></fieldset>}<label>{form.frequency === 'monthly' ? 'Starts on (day of month repeats)' : 'Starts'}<input required type="date" value={form.starts_at} onChange={e => change('starts_at', e.target.value)} /></label></section>}
        <details className="planner-more-options"><summary>More options</summary><div><label>Brief<textarea value={form.brief} onChange={e => change('brief', e.target.value)} placeholder="Optional context" /></label><label>Assigned agent<input value={form.assigned_agent} onChange={e => change('assigned_agent', e.target.value)} placeholder="Optional worker id" /></label>{type === 'recurring' && <label>End date<input type="date" value={form.ends_at} onChange={e => change('ends_at', e.target.value)} /></label>}<div className="planner-form-grid"><label>Generation<select value={form.generation_mode} onChange={e => change('generation_mode', e.target.value)}><option value="manual">Manual</option><option value="automatic">Automatic preference</option></select></label><label>Publishing<select value={form.publishing_mode} onChange={e => change('publishing_mode', e.target.value)}><option value="review">Review first</option><option value="automatic">Automatic preference</option></select></label></div></div></details>
        <p className="planner-summary"><b>{summary}</b><span>{brand?.name || 'Choose a workspace'} · {form.platform} · {form.content_type}</span></p>
        {error && <p className="planner-form-error">{error}</p>}<footer><small>{TZ} · Scheduling only; no worker is triggered.</small><button disabled={saving}>{saving ? 'Saving…' : 'Save schedule'}</button></footer>
    </form></div>;
}

function AiPlanModal({ brands, onClose, onAnalyze, onSave }) {
    const [prompt, setPrompt] = useState('');
    const [result, setResult] = useState(null);
    const [loading, setLoading] = useState(false);
    const [saving, setSaving] = useState(false);
    const [error, setError] = useState(null);
    const analyze = async (event) => { event.preventDefault(); setLoading(true); setError(null); try { setResult(await onAnalyze(prompt)); } catch (caught) { setError(caught.message || 'Planner could not analyze this request.'); } finally { setLoading(false); } };
    const confirm = async () => { setSaving(true); setError(null); try { for (const item of result.plan.items) await onSave(item); onClose(); } catch (caught) { setError(caught.message || 'Could not save this schedule preview.'); } finally { setSaving(false); } };
    return <div className="planner-modal-wrap"><button type="button" className="planner-modal-scrim" onClick={onClose} aria-label="Close AI Plan" /><section className="planner-modal ai-plan-modal"><header><div><span>AI PLAN</span><h2>Plan content with AI</h2></div><button type="button" onClick={onClose}><X size={18} /></button></header>{!result ? <form onSubmit={analyze}><p>Tell the Analyst what you want to schedule. It will only create a preview.</p><textarea required minLength="8" value={prompt} onChange={event => setPrompt(event.target.value)} placeholder="Every Monday create a Kauiz feed at 19:00 and a story at 12:00 about study tips." /><small>Schedules are never generated or published from this step.</small>{error && <p className="planner-form-error">{error}</p>}<footer><span /><button disabled={loading}>{loading ? 'Analyzing…' : 'Analyze plan'}</button></footer></form> : <div className="ai-plan-preview">{result.clarifications?.length > 0 && <div className="ai-clarifications"><b>Needs clarification</b>{result.clarifications.map(item => <p key={item}>{item}</p>)}</div>}{result.plan.items.map((item, index) => { const brand = brands.find(candidate => candidate.id === item.brand_id); return <article key={`${item.name}-${index}`}><em>{brand?.name || 'Workspace'}</em><b>{item.platform} · {item.content_type}</b><strong>{item.topic || item.name}</strong><small>{item.schedule_type === 'recurring' ? `${item.frequency === 'weekly' ? `Every ${item.days.map(day => ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][day - 1]).join(', ')}` : `Every ${item.frequency}`} · ${item.time}` : prettyDate(item.scheduled_at)}</small><span>{item.schedule_type === 'recurring' ? 'Recurring' : 'One-time'}</span></article>})}{error && <p className="planner-form-error">{error}</p>}<footer><button type="button" className="ai-back" onClick={() => setResult(null)}>Back / Edit</button><button disabled={saving || result.plan.items.length === 0} onClick={confirm}>{saving ? 'Saving…' : 'Confirm schedule'}</button></footer></div>}</section></div>;
}

export function ContentPlanner({ planner, brands, loading, loadPlanner, createSchedule, analyzePlan }) {
    const [cursor, setCursor] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1));
    const [formType, setFormType] = useState(null);
    const [brandFilter, setBrandFilter] = useState('all');
    const [aiPlanOpen, setAiPlanOpen] = useState(false);
    const start = new Date(cursor.getFullYear(), cursor.getMonth(), 1);
    const end = new Date(cursor.getFullYear(), cursor.getMonth() + 1, 0);
    useEffect(() => { loadPlanner(start.toISOString().slice(0, 10), end.toISOString().slice(0, 10)).catch(() => {}); }, [cursor]);
    const days = useMemo(() => Array.from({ length: end.getDate() }, (_, index) => new Date(cursor.getFullYear(), cursor.getMonth(), index + 1)), [cursor]);
    const visibleOccurrences = useMemo(() => (planner?.occurrences || []).filter(item => brandFilter === 'all' || item.brand?.id === brandFilter), [planner, brandFilter]);
    const visibleUpcoming = useMemo(() => (planner?.upcoming || []).filter(item => brandFilter === 'all' || item.brand?.id === brandFilter), [planner, brandFilter]);
    const byDay = useMemo(() => visibleOccurrences.reduce((result, item) => { const key = dateKey(item.scheduledAt); result[key] = [...(result[key] || []), item]; return result; }, {}), [visibleOccurrences]);
    const monthTitle = new Intl.DateTimeFormat('id-ID', { month: 'long', year: 'numeric' }).format(cursor);
    return <div className="content-view planner-view"><div className="view-heading"><div><span>CONTENT PLANNER</span><h1>Content Planner</h1><p>Calendar-based schedules in {TZ}. Saving a schedule never starts a worker.</p></div><div className="planner-actions"><button onClick={() => setFormType('one_time')}><Plus size={15} /> One-time</button><button onClick={() => setFormType('recurring')}><Repeat2 size={15} /> Recurring</button><button onClick={() => setAiPlanOpen(true)}><Sparkles size={15} /> AI Plan</button></div></div>
        <div className="planner-filter"><span>Workspace</span><select value={brandFilter} onChange={event => setBrandFilter(event.target.value)}><option value="all">All Brands</option>{brands.map(brand => <option key={brand.id} value={brand.id}>{brand.name}</option>)}</select></div>
        <section className="planner-layout"><div className="planner-calendar"><header><div><button onClick={() => setCursor(new Date(cursor.getFullYear(), cursor.getMonth() - 1, 1))} aria-label="Bulan sebelumnya"><ChevronLeft size={18} /></button><strong>{monthTitle}</strong><button onClick={() => setCursor(new Date(cursor.getFullYear(), cursor.getMonth() + 1, 1))} aria-label="Bulan berikutnya"><ChevronRight size={18} /></button></div><small>{visibleOccurrences.length} visible occurrences</small></header><div className="calendar-weekdays">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map(day => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{Array.from({ length: (start.getDay() + 6) % 7 }, (_, index) => <i key={`gap-${index}`} />)}{days.map(day => { const entries = byDay[dateKey(day)] || []; return <article key={day.toISOString()} className={dateKey(day) === dateKey(new Date()) ? 'today' : ''}><time>{day.getDate()}</time>{entries.slice(0, 3).map(item => <div className={`calendar-item ${item.scheduleType}`} title={`${item.brand?.name || 'No workspace'} · ${item.name} · ${prettyDate(item.scheduledAt)}`} key={item.id}><em>{item.brand?.name || 'Unassigned'}</em><b>{item.name}</b><small>{item.platform} · {item.contentType}</small><small>{item.scheduleType === 'recurring' ? `↻ ${item.recurrenceLabel}` : 'One-time'}</small></div>)}{entries.length > 3 && <small className="calendar-more">+{entries.length - 3} more</small>}</article>; })}</div></div><aside className="planner-upcoming"><header><CalendarDays size={16} /><div><span>UPCOMING</span><strong>Next scheduled content</strong></div></header>{loading ? <p>Loading schedules…</p> : visibleUpcoming.length ? visibleUpcoming.map(item => <article key={item.id}><div><em>{item.brand?.name || 'Unassigned'}</em><b>{item.name}</b><small>{item.platform} · {item.contentType}</small>{item.topic && <small>{item.topic}</small>}</div><time>{prettyDate(item.scheduledAt)}</time><span className={item.scheduleType}>{item.scheduleType === 'recurring' ? item.recurrenceLabel : 'One-time'}</span></article>) : <p>No content scheduled in this visible month.</p>}</aside></section>
        {formType && <PlannerForm type={formType} brands={brands} onClose={() => setFormType(null)} onSave={createSchedule} />}
        {aiPlanOpen && <AiPlanModal brands={brands} onClose={() => setAiPlanOpen(false)} onAnalyze={analyzePlan} onSave={createSchedule} />}
    </div>;
}
