import test from 'node:test';import assert from 'node:assert/strict';
import { normalizeRoster,auditRoster } from '../../resources/js/living-office/preview3d/full/roster.js';
import { makeWorld,syncWorld,stepWorld,requestDestination,route,graph,furnitureCollision } from '../../resources/js/living-office/preview3d/full/navigation.js';
import { stations,canonicalRooms } from '../../resources/js/living-office/preview3d/full/layout.js';
const ids=['trent','jauki-social','jauki-threads','jauki-article','jauki-planner','jauki-analyst','data-analyst','finance-analyst'];
const rows=ids.map(id=>({id,status:'idle',currentTask:'',progress:0}));const roster=()=>normalizeRoster(rows).workers;
function run(world,done,limit=30000){let crossed=false;for(let i=0;i<limit;i++){const prev=new Map([...world.motions].map(([id,m])=>[id,[m.x,m.z]]));stepWorld(world,1/30,{ambience:false});for(const m of world.motions.values()){for(const other of world.motions.values())if(other.id!==m.id)assert.ok(Math.hypot(m.x-other.x,m.z-other.z)>=.5,'personal space respected');assert.equal(furnitureCollision(m.x,m.z),false,`${m.id} inside furniture ${m.x},${m.z}`);for(const r of canonicalRooms){if(Math.abs(m.x-r.doorX)<.8&&Math.abs(m.z-r.front)<.3&&m.moving){assert.ok(world.doors.get(r.id).open>.95);crossed=true;}}}if(done())return crossed;}assert.fail(JSON.stringify([...world.motions.values()].map(m=>({id:m.id,phase:m.phase,x:m.x,z:m.z,target:m.target,index:m.index}))))}
test('all 8 backend IDs represented with unique home stations; refresh preserves models and position',()=>{const world=makeWorld(roster());assert.deepEqual(auditRoster(roster(),world.motions,world.assignments),{authoritative:8,rendered:8,missing:[],extra:[],duplicateStations:[],unassigned:[]});const m=world.motions.get('jauki-social');m.x+=.1;syncWorld(world,normalizeRoster(rows.map(r=>({...r,currentTask:'Updated'}))).workers);assert.equal(world.motions.get(m.id),m);assert.equal(m.x,6.1);assert.equal(m.worker.task,'Updated');});
test('every station connected without desk collisions',()=>{for(const s of stations){let prev=graph.nodes.get(s.id).p;for(const point of route(s.id,'recreation-1')){for(let i=0;i<=20;i++)assert.equal(furnitureCollision(prev[0]+(point.p[0]-prev[0])*i/20,prev[1]+(point.p[1]-prev[1])*i/20),false,s.id);prev=point.p;}}});
test('idle visit enters corridor, door opens, then worker returns seated',()=>{const world=makeWorld(roster()),m=world.motions.get('jauki-planner');requestDestination(world,m.id,'recreation-1');assert.ok(run(world,()=>m.phase==='idle'));run(world,()=>m.phase==='seated'&&m.station===m.home);assert.equal(m.seated,1);});
test('two workers share meeting door without duplication or collision',()=>{const world=makeWorld(roster());const a=world.motions.get('jauki-social'),b=world.motions.get('jauki-threads');requestDestination(world,a.id,'meeting-1');requestDestination(world,b.id,'meeting-5');run(world,()=>a.phase==='seated'&&b.phase==='seated'&&a.station==='meeting-1'&&b.station==='meeting-5');});
test('domain meeting, break and active task return use actual status, stale retains roster',()=>{const world=makeWorld(roster());syncWorld(world,normalizeRoster(rows.map(r=>r.id==='jauki-planner'?{...r,status:'meeting'}:r),{stale:true}).workers);const m=world.motions.get('jauki-planner');assert.match(m.target,/meeting/);run(world,()=>m.phase==='seated');syncWorld(world,normalizeRoster(rows.map(r=>r.id===m.id?{...r,status:'working',currentTask:'Actual API task'}:r)).workers);run(world,()=>m.phase==='seated'&&m.station===m.home);assert.equal(m.worker.task,'Actual API task');});
test('unavailable workers remain visible; reduced motion does not trigger ambient walking',()=>{const world=makeWorld(normalizeRoster(rows.map(r=>({...r,status:'not_connected'}))).workers);for(let i=0;i<50000;i++)stepWorld(world,.05,{reduced:true});assert.equal(world.motions.size,8);assert.ok([...world.motions.values()].every(m=>m.phase==='seated'));});
test('opposite door traffic clears; task update mid-route does not teleport',()=>{const world=makeWorld(roster()),a=world.motions.get('jauki-planner'),b=world.motions.get('jauki-threads');requestDestination(world,b.id,'content-2');run(world,()=>b.phase==='seated'&&b.station==='content-2');requestDestination(world,a.id,'threads-2');requestDestination(world,b.id,'meeting-2');run(world,()=>a.phase==='seated'&&a.station==='threads-2'&&b.phase==='seated'&&b.station==='meeting-2');});
test('rest and server rooms reachable and occupants remain separated',()=>{const world=makeWorld(roster()),a=world.motions.get('jauki-planner'),b=world.motions.get('trent');requestDestination(world,a.id,'lounge-1');requestDestination(world,b.id,'server-monitor');run(world,()=>a.phase==='seated'&&a.station==='lounge-1'&&b.phase==='seated'&&b.station==='server-monitor');});
test('refresh during walking preserves position; task arrival while sitting queues return without teleport',()=>{const world=makeWorld(roster()),m=world.motions.get('jauki-planner');requestDestination(world,m.id,'meeting-1');run(world,()=>m.phase==='walking');const x=m.x,z=m.z;syncWorld(world,normalizeRoster(rows.map(r=>({...r,currentTask:'New read-only task text'}))).workers);assert.equal(m.x,x);assert.equal(m.z,z);run(world,()=>m.phase==='sitting');syncWorld(world,normalizeRoster(rows.map(r=>r.id===m.id?{...r,status:'working'}:r)).workers);for(let i=0;i<15000;i++){const before=[m.x,m.z];stepWorld(world,1/30,{ambience:false});assert.ok(Math.hypot(m.x-before[0],m.z-before[1])<.15,'no teleport during seat interruption');if(m.phase==='seated'&&m.station===m.home)return;}assert.fail('worker did not return home');});
test('reduced motion completes a real room journey while disabling idle roaming',()=>{const world=makeWorld(roster()),m=world.motions.get('jauki-planner');requestDestination(world,m.id,'meeting-1');for(let i=0;i<20000;i++){stepWorld(world,1/30,{reduced:true});assert.equal(furnitureCollision(m.x,m.z),false);if(m.phase==='seated'&&m.station==='meeting-1')break;}assert.equal(m.station,'meeting-1');assert.equal(m.seated,1);for(let i=0;i<50000;i++)stepWorld(world,.05,{reduced:true});assert.ok([...world.motions.values()].every(w=>w.phase==='seated'));});
